# Generated by Django 5.0.8 on 2024-08-11 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('JUSTICE', 'Justice'), ('HEALTH', 'Health'), ('EDUCATION', 'Education'), ('ENVIRONMENT', 'Environment'), ('ECONOMY', 'Economy'), ('INTERNATIONAL', 'International'), ('SPORT', 'Sport'), ('CIVIL', 'Civil'), ('SCIENCE', 'Science')], help_text='Select a category', max_length=255)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, help_text='Email address', max_length=255, null=True)),
                ('address', models.CharField(blank=True, help_text='Physical address', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='Phone number', max_length=255)),
                ('is_whatsapp', models.BooleanField(default=False, help_text='Is this a WhatsApp number?')),
                ('is_calling', models.BooleanField(default=False, help_text='Is this a calling number?')),
                ('is_messaging', models.BooleanField(default=False, help_text='Is this a messaging number?')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField()),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='core.contact')),
            ],
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the procedure', max_length=255)),
                ('slug', models.SlugField(default='', editable=False, max_length=200)),
                ('description', models.TextField(help_text='Description of the procedure')),
                ('estimated_time_to_complete', models.DurationField(help_text='Estimated time to complete')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of the procedure', max_digits=10)),
                ('status', models.CharField(choices=[], help_text='Select a status', max_length=255)),
                ('is_visible', models.BooleanField(default=True, help_text='Is this procedure visible?')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField()),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='core.category')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload an image: <strong>.PNG, .JPG</strong> file', upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField()),
                ('procedure', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.procedure')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the document', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the document', null=True)),
                ('file', models.ImageField(help_text='Upload a document: <strong>.PNG, .JPG</strong> file', upload_to='documents/')),
                ('type', models.CharField(choices=[], help_text='Select a document type', max_length=255)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField()),
                ('procedure', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.procedure')),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='procedure',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='core.procedure'),
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of availability')),
                ('from_time', models.TimeField(help_text='Available from')),
                ('to_time', models.TimeField(help_text='Available to')),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField()),
                ('procedure', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='core.procedure')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Select a category', max_length=255)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField()),
                ('procedure', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='core.procedure')),
            ],
        ),
    ]
