# Generated by Django 5.0.8 on 2024-08-16 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='joelfah', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
